version: 0.2

phases:
  install:
    commands:
      - echo "Installing dependencies..."

  pre_build:
    commands:
      - echo "Validating CloudFormation template..."
      - aws cloudformation validate-template --template-body file://cloudformation/storage/s3.yaml

  build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - cloudformation/storage/s3.yaml
    - cloudformation/master.yaml
    - parameters/**/*.json
  discard-paths: no