#CloudFormation template format version.
AWSTemplateFormatVersion: '2010-09-09'

#description that appears in the CloudFormation console.
Description: S3 Bucket for Application Logs

#AWS resource is defined here.
Resources:

  AppLogsBucket:

    #This tells CloudFormation which AWS resource to create.
    Type: AWS::S3::Bucket

    Properties:

      BucketName: nike-dev-app-logs-001

      #Versioning protects against accidental overwrites or deletions and is commonly enabled in production.
      VersioningConfiguration:

        Status: Enabled

      Tags:

        - Key: Environment
          Value: Development

        - Key: Project
          Value: Nike

        - Key: Owner
          Value: DevOps
